const quotes = [
  "Discomfort is the birthplace of growth.",
  "Your future self is watching—don’t disappoint them.",
  "Courage isn’t loud; it’s often a quiet choice to keep going.",
  "Small consistent steps beat bursts of effort followed by silence.",
  "Discipline is remembering what you want most, not what you want now.",
  "Dreams only work if you do.",
  "Your excuses are perfectly designed to keep you average.",
  "Fall in love with the process, and results will follow.",
  "Success is built from boring days done well.",
  "Energy flows where attention goes.",
  "Doubt kills more dreams than failure ever could.",
  "Comfort zones are prisons disguised as safety.",
  "Your only competition is yesterday’s version of you.",
  "The habit you avoid is the one you need most.",
  "Win the morning, win the day.",
  "Effort compounds like interest—keep depositing daily.",
  "Fear is excitement without breath—breathe through it.",
  "The hardest battles are invisible but they shape you most.",
  "A year from now, you’ll wish you had started today.",
  "Hustle in silence, let success be the noise.",
  "Your mess can become your message.",
  "Motivation gets you started; discipline keeps you moving.",
  "Your environment is stronger than your willpower—choose wisely.",
  "What you do when no one’s watching defines you.",
  "Great things are built on hundreds of unnoticed small wins.",
  "Consistency makes the extraordinary look ordinary.",
  "Clarity comes from action, not overthinking.",
  "You can’t control the wind, but you can adjust the sail.",
  "Don’t fear failure—fear staying the same.",
  "Sacrifice now or regret later—the choice is yours.",
  "You don’t need more time; you need more focus.",
  "Comfort never produced greatness.",
  "Your struggles today are the stories you’ll inspire with tomorrow.",
  "Discipline is choosing between what you want now and what you want most.",
  "The gap between goals and success is filled with discipline.",
  "A comfort zone is a beautiful place, but nothing grows there.",
  "You are stronger than the sum of your excuses.",
  "Big journeys begin with small, stubborn steps.",
  "The heaviest weight you’ll ever lift is your own doubt.",
  "If it doesn’t challenge you, it won’t change you.",
  "Excuses are nails that build the house of failure.",
  "Time you enjoy wasting isn’t wasted—but be intentional.",
  "Your dreams don’t work unless you do.",
  "Pressure creates diamonds; don’t run from it.",
  "Start where you are, use what you have, do what you can.",
  "Don’t count the days, make the days count.",
  "You can’t climb the ladder of success with hands in your pockets.",
  "Comfort is addictive—break free before it breaks you.",
  "You don’t have to be extreme, just consistent.",
  "Prove your past self wrong, not others.",
  "Failure is data, not identity.",
  "Discipline is the bridge between intention and reality.",
  "Your future is created by what you do today, not tomorrow.",
  "Excuses are a form of self-sabotage dressed politely.",
  "Energy without direction is wasted potential.",
  "Don’t be upset by the results you didn’t get from the work you didn’t do.",
  "Most overnight successes took years of daily grind.",
  "You don’t rise to the level of your goals; you fall to the level of your systems.",
  "Hard choices, easy life. Easy choices, hard life.",
  "Confidence comes from keeping promises to yourself.",
  "Don’t chase motivation—build habits.",
  "You either suffer the pain of discipline or the pain of regret.",
  "Small progress is still progress—don’t discount it.",
  "Excuses make today easy but tomorrow hard.",
  "Invest in your mind, it pays the best interest.",
  "Sweat more in practice, bleed less in battle.",
  "Most people quit when they’re 90% there.",
  "Don’t stop when you’re tired, stop when you’re done.",
  "Your comfort today can be your cage tomorrow.",
  "Direction is more important than speed.",
  "What consumes your mind controls your life.",
  "Growth begins at the edge of fear.",
  "Excuses are confessions of laziness.",
  "What you do daily is who you become permanently.",
  "There is no elevator to success—you have to take the stairs.",
  "Be addicted to progress, not perfection.",
  "Don’t mistake movement for progress.",
  "Sacrifice what you want now for what you want most.",
  "Champions train when no one is watching.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Your failures are stepping stones, not tombstones.",
  "Most limits exist only in your mind.",
  "Don’t adapt to the energy in the room, influence it.",
  "Excuses are the enemy of execution.",
  "Your rituals define your results.",
  "Every day is a vote for the person you’re becoming.",
  "Stop waiting for the perfect moment—it doesn’t exist.",
  "Effort never betrays you.",
  "Discomfort is proof you’re on the right path.",
  "Excuses multiply; results compound.",
  "Persistence eats resistance.",
  "Be stronger than your strongest excuse.",
  "Your legacy is built one decision at a time.",
  "Stop wishing. Start doing.",
  "Your dream job won’t apply for you.",
  "Success tastes better after sacrifice.",
  "Nobody cares, work harder.",
  "Your energy introduces you before you speak.",
  "Start small, stay consistent, grow unstoppable.",
  "Excuses keep doors closed; effort unlocks them."
];


function generateQuote() {
  // Pick a random quote
  const randomIndex = Math.floor(Math.random() * quotes.length);
  document.getElementById("quote").textContent = quotes[randomIndex];

  // Random background color
  const randomColor = `hsl(${Math.floor(Math.random() * 360)}, 70%, 80%)`;
  document.body.style.background = randomColor;
}
